sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: jPOvekUwlwbaBCTdQskjnBh1aAnh/tW/Re+oR0GWghzoSfhAxxn6kwPp0kRa3+vk64E/LTNE10xqrH86Ywt9dgplQLqT8R3An501ry+F1dRadXaxmCxYpp8x3Qq708fjhf6Mts5/mLAqCXVrsZXXja3+GZi/z0VHfKQBugkwAAKhNrGkcF3+kZ9ttQ6KJ7Jm/Dj2UtKj87SE+MZU2L+yAXIk34KrdCBDH31mxE6OpMXAo/oVrdVHZyd4EHOyXt9wW7RdEEb2XBl+FCIhpsJ+6vNUa5iJ1WLqCW0d4oYnALLFylHp82BaMebN9kMja5ooFwVssO31v9kB8jitIkxzzizWwQRekqhdAvuGqqUceKdahIEO3sioc7m/vqa9FSmuvDk8BCTv/9hY6DbKwjqkB79rWL5p5AsADOjXIRf4NuEf6KpU7TyaOjzGqNrmHj6mANerfoZeiJwHnD31xlUSWg52bU8Vggy0242+CmSb3v55xQVbh/tjm7WUXU7rEVXEIdy3jn0FmtbUmt5+CGSgDW3Xu9z5wiTH8NtbPVnpZTeskn4yEJ7kyJXadABZSOBQrrAza208elrl2HP2JvScOusywz04/wourQCUUMlnB5A/sEifbVqHv4U4iIh/kDNJ6R9yMM698hdyhzxaU9/fHnthV9ZrF1uh7jTf9gL06AM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Coming-Race_1951
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy